version: '2.1'
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build:
    docker:
      - image: maven:3.8.1-openjdk-17-slim
    steps:
      - checkout
      - run: mvn clean package -Pproduction -DskipTests -Dvaadin.offlineKey=$VAADIN_OFFLINE_KEY
      - store_artifacts:
          path: target
          destination: target

  build-docker-image:
    docker:
      - image: cimg/azure:2025.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker Build & Push
          command: |
            docker build --build-arg VAADIN_OFFLINE_KEY=$VAADIN_OFFLINE_KEY -t vaadindockercontainer.azurecr.io/vaadincrm:latest .
            echo $DOCKER_PASS | docker login vaadindockercontainer.azurecr.io -u $DOCKER_USER --password-stdin
            docker push vaadindockercontainer.azurecr.io/vaadincrm:latest
      - run:
          name: Update Azure Web App
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            az webapp config container set \
              --name $AZURE_WEBAPP_NAME \
              --resource-group $AZURE_RESOURCE_GROUP \
              --docker-custom-image-name vaadindockercontainer.azurecr.io/vaadincrm:latest \
              --docker-registry-server-url https://vaadindockercontainer.azurecr.io \
              --docker-registry-server-user $DOCKER_USER \
              --docker-registry-server-password $DOCKER_PASS

workflows:
  deploy:
    jobs:
      - build
      - build-docker-image:
          requires:
            - build
